{
  "openapi": "3.0.0",
  "info": {
    "title": "API PagarMe V4",
    "description": "Essa API foi criada com o intuito de ajudar pessoas a integrar o Gateway da PagarMe em seus projetos NodeJS.",
    "termsOfService": "API Terms",
    "contact": {
      "email": "jrsousadev@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/",
      "description": "API Testing"
    }
  ],
  "paths": {
    "/api/cart": {
      "post": {
        "summary": "Create Cart",
        "description": "This route will be responsible for creating a cart",
        "tags": ["Cart"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CartRequest"
              },
              "examples": {
                "cart": {
                  "value": {
                    "code": "di42145-49154d-dz495d-5eijd4",
                    "price": 200
                  }
                }
              }
            }
          }
        },
        "responses": {}
      },

      "get": {
        "summary": "Get Carts",
        "description": "This route will be responsible for picking up all the carts",
        "tags": ["Cart"],
        "responses": {}
      }
    },
    "/api/cart/{id}": {
      "put": {
        "summary": "Update Cart",
        "description": "This route will be responsible for updating the cart",
        "tags": ["Cart"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Cart ID to update",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CartRequest"
              },
              "examples": {
                "cart": {
                  "value": {
                    "code": "di42145-49154d-dz495d-44444",
                    "price": 450
                  }
                }
              }
            }
          }
        },
        "responses": {}
      },

      "get": {
        "summary": "Get one Cart",
        "description": "This route will be responsible for picking up a cart",
        "tags": ["Cart"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Cart ID to delete",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {}
      },

      "delete": {
        "summary": "Delete Cart",
        "description": "This route will be responsible for deleting the cart",
        "tags": ["Cart"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Cart ID to delete",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {}
      }
    },
    "/api/transaction": {
      "post": {
        "summary": "Create Transaction",
        "description": "This route will be responsible for creating a transaction",
        "tags": ["Transaction"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionRequest"
              },
              "examples": {
                "transaction credit_card": {
                  "value": {
                    "cartCode": "4oek3e-dudqozd-dudkflz-oeiwe",
                    "paymentType": "credit_card",
                    "installments": 6,
                    "customerName": "Fulano Example",
                    "customerEmail": "example@example.com",
                    "customerMobile": "(11) 11111-1111",
                    "customerDocument": "111.111.111-11",
                    "billingAddress": "Address",
                    "billingNumber": "123",
                    "billingNeighborhood": "Center",
                    "billingCity": "São Paulo",
                    "billingState": "SP",
                    "billingZipCode": "11111-111",
                    "billingComplementary": "Complementary",
                    "creditCardNumber": "4111111111111111",
                    "creditCardExpiration": "08/23",
                    "creditCardHolderName": "Holder Name",
                    "creditCardCvv": "123"
                  }
                },
                "transaction billet": {
                  "value": {
                    "cartCode": "4oek3e-dudqozd-dudkflz-oeiwe",
                    "paymentType": "billet",
                    "installments": 1,
                    "customerName": "Fulano Example",
                    "customerEmail": "example@example.com",
                    "customerMobile": "(11) 11111-1111",
                    "customerDocument": "111.111.111-11",
                    "billingAddress": "Address",
                    "billingNumber": "123",
                    "billingNeighborhood": "Center",
                    "billingCity": "São Paulo",
                    "billingState": "SP",
                    "billingZipCode": "11111-111",
                    "billingComplementary": "Complementary"
                  }
                },
                "transaction pix": {
                  "value": {
                    "cartCode": "4oek3e-dudqozd-dudkflz-oeiwe",
                    "paymentType": "pix",
                    "installments": 1,
                    "customerName": "Fulano Example",
                    "customerEmail": "example@example.com",
                    "customerMobile": "(11) 11111-1111",
                    "customerDocument": "111.111.111-11",
                    "billingAddress": "Address",
                    "billingNumber": "123",
                    "billingNeighborhood": "Center",
                    "billingCity": "São Paulo",
                    "billingState": "SP",
                    "billingZipCode": "11111-111",
                    "billingComplementary": "Complementary",
                    "pixExpirationDate": "2022-12-25T15:00:00"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      },
      "get": {
        "summary": "Get Transactions",
        "description": "This route will be responsible for picking up all the transactions",
        "tags": ["Transaction"],
        "responses": {}
      }
    },
    "/api/postbacks/pagarme/{tokenAccess}": {
      "post": {
        "summary": "Update Status Transaction - PagarMe Webhook",
        "description": "This route will be responsible for updating the status of transactions through the PagarMe request",
        "tags": ["Postback"],
        "parameters": [
          {
            "name": "tokenAccess",
            "in": "path",
            "description": "tokenAccess to authorization updated status",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostbackRequest"
              },
              "examples": {
                "postback": {
                  "value": {
                    "id": "4219582421",
                    "object": "transaction",
                    "current_status": "paid"
                  }
                }
              }
            }
          }
        },
        "responses": {}
      }
    }
  },

  "components": {
    "schemas": {
      "TransactionRequest": {
        "type": "object",
        "properties": {
          "cartCode": {
            "type": "string"
          },
          "paymentType": {
            "type": "string",
            "enum": ["billet", "credit_card", "pix"]
          },
          "installments": {
            "type": "integer",
            "minimum": 1,
            "maximum": 12
          },
          "customerName": {
            "type": "string"
          },
          "customerEmail": {
            "type": "string"
          },
          "customerMobile": {
            "type": "string"
          },
          "customerDocument": {
            "type": "string"
          },
          "billingAddress": {
            "type": "string"
          },
          "billingNumber": {
            "type": "string"
          },
          "billingNeighborhood": {
            "type": "string"
          },
          "billingCity": {
            "type": "string"
          },
          "billingState": {
            "type": "string"
          },
          "billingZipCode": {
            "type": "string"
          },
          "billingComplementary": {
            "type": "string"
          },
          "creditCardNumber": {
            "type": "string",
            "required": false
          },
          "creditCardExpiration": {
            "type": "string",
            "required": false
          },
          "creditCardHolderName": {
            "type": "string",
            "required": false
          },
          "creditCardCvv": {
            "type": "string",
            "required": false
          },
          "pixExpirationDate": {
            "type": "date",
            "required": "false"
          }
        }
      },
      "CartRequest": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "price": {
            "type": "number"
          }
        }
      },
      "PostbackRequest": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "object": {
            "type": "string",
            "enum": ["transaction"]
          },
          "current_status": {
            "type": "string"
          }
        }
      }
    }
  }
}
